/********************************************************* NOTE *********************************************************/
/*
 * I used the v6 version and renamed "v6" to "v1" in this file to get it to work because the XML has "v1" as the namespace in the header
 * Ex: <?xml version="1.0" encoding="UTF-8"?><OASISReport xmlns="http://www.caiso.com/soa/OASISReport_v1.xsd">
 */
/************************************************************************************************************************/

namespace Prices.Core.Application.XsdClasses.Report.V1;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd", IsNullable=false)]
public partial class OASISReport {
    
    private MessageHeader messageHeaderField;
    
    private MessagePayload messagePayloadField;
    
    /// <remarks/>
    public MessageHeader MessageHeader {
        get {
            return this.messageHeaderField;
        }
        set {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    public MessagePayload MessagePayload {
        get {
            return this.messagePayloadField;
        }
        set {
            this.messagePayloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class MessageHeader {
    
    private string timeDateField;
    
    private string sourceField;
    
    private string versionField;
    
    public MessageHeader() {
        this.versionField = "v20171001";
    }
    
    /// <remarks/>
    public string TimeDate {
        get {
            return this.timeDateField;
        }
        set {
            this.timeDateField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class ERROR {
    
    private System.Nullable<OASISErrCode> eRR_CODEField;
    
    private bool eRR_CODEFieldSpecified;
    
    private System.Nullable<OASISErrDescription> eRR_DESCField;
    
    private bool eRR_DESCFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<OASISErrCode> ERR_CODE {
        get {
            return this.eRR_CODEField;
        }
        set {
            this.eRR_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ERR_CODESpecified {
        get {
            return this.eRR_CODEFieldSpecified;
        }
        set {
            this.eRR_CODEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<OASISErrDescription> ERR_DESC {
        get {
            return this.eRR_DESCField;
        }
        set {
            this.eRR_DESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ERR_DESCSpecified {
        get {
            return this.eRR_DESCFieldSpecified;
        }
        set {
            this.eRR_DESCFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum OASISErrCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1000")]
    Item1000,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1001")]
    Item1001,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1002")]
    Item1002,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1003")]
    Item1003,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1004")]
    Item1004,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1005")]
    Item1005,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1006")]
    Item1006,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1007")]
    Item1007,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1008")]
    Item1008,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1009")]
    Item1009,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1010")]
    Item1010,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1011")]
    Item1011,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1012")]
    Item1012,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1013")]
    Item1013,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1014")]
    Item1014,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1015")]
    Item1015,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1016")]
    Item1016,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1017")]
    Item1017,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1018")]
    Item1018,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1019")]
    Item1019,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1020")]
    Item1020,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum OASISErrDescription {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("No data returned for the specified selection")]
    Nodatareturnedforthespecifiedselection,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid Parameters of the given report name")]
    InvalidParametersofthegivenreportname,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid datetime format, please use valid datetime format")]
    Invaliddatetimeformatpleaseusevaliddatetimeformat,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Timed out waiting for query response")]
    Timedoutwaitingforqueryresponse,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Data can be requested for period of 31 days only")]
    Datacanberequestedforperiodof31daysonly,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Report name does not exist, please use valid report name")]
    Reportnamedoesnotexistpleaseusevalidreportname,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Validation exception during transformation of XML")]
    ValidationexceptionduringtransformationofXML,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Required file does not exist")]
    Requiredfiledoesnotexist,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Out of memory exception")]
    Outofmemoryexception,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Exceptions in reading and writing of XML files")]
    ExceptionsinreadingandwritingofXMLfiles,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System Error")]
    SystemError,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Empty Query,Please Enter ReportName,Startdate,EndDate and Other Parameters")]
    EmptyQueryPleaseEnterReportNameStartdateEndDateandOtherParameters,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Connection refused")]
    Connectionrefused,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Required Resources(xslt or xml or dir)Unavailable")]
    RequiredResourcesxsltorxmlordirUnavailable,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Start Date is beyond the limit, Please Use valid Start Date that falls within the" +
        " prescribed limit")]
    StartDateisbeyondthelimitPleaseUsevalidStartDatethatfallswithintheprescribedlimit,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GroupZip DownLoad is in Processing, Please Submit request after Sometime")]
    GroupZipDownLoadisinProcessingPleaseSubmitrequestafterSometime,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GROUPID Does Not Exist, Please Use Valid GROUPID Name")]
    GROUPIDDoesNotExistPleaseUseValidGROUPIDName,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Please select a maximum of 10 nodes or use the ALL option")]
    Pleaseselectamaximumof10nodesorusetheALLoption,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid Selection, cannot select multiple hours for this query")]
    InvalidSelectioncannotselectmultiplehoursforthisquery,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("market_term=ALL not supported for this query")]
    market_termALLnotsupportedforthisquery,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Version parameter is missing or is invalid")]
    Versionparameterismissingorisinvalid,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class DISCLAIMER_ITEMRq {
    
    private string dISCLAIMERField;
    
    /// <remarks/>
    public string DISCLAIMER {
        get {
            return this.dISCLAIMERField;
        }
        set {
            this.dISCLAIMERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class REPORT_DATAOASIS {
    
    private OASISDataItems dATA_ITEMField;
    
    private string sOURCEField;
    
    private string sINKField;
    
    private string rESOURCE_NAMEField;
    
    private string dIRECTIONField;
    
    private string? oPR_DATEField;
    
    private bool oPR_DATEFieldSpecified;
    
    private string? gAS_FLOW_DATEField;
    
    private bool gAS_FLOW_DATEFieldSpecified;
    
    private string iNTERVAL_NUMField;
    
    private string? iNTERVAL_START_GMTField;
    
    private bool iNTERVAL_START_GMTFieldSpecified;
    
    private string? iNTERVAL_END_GMTField;
    
    private bool iNTERVAL_END_GMTFieldSpecified;
    
    private string pHYSICAL_TYPEField;
    
    private System.Nullable<double> mAXIMUM_LIMITField;
    
    private bool mAXIMUM_LIMITFieldSpecified;
    
    private System.Nullable<double> mINIMUM_LIMITField;
    
    private bool mINIMUM_LIMITFieldSpecified;
    
    private string lIMIT_TYPEField;
    
    private string cONSTRAINT_GROUP_NAMEField;
    
    private System.Nullable<double> vALUEField;
    
    private bool vALUEFieldSpecified;
    
    private string sVALUEField;
    
    private string oPTIONField;
    
    private string? iNVENTORY_DATE_TIMEField;
    
    private bool iNVENTORY_DATE_TIMEFieldSpecified;
    
    private string? iNVENTORY_DATE_TIME_GMTField;
    
    private bool iNVENTORY_DATE_TIME_GMTFieldSpecified;
    
    private string? sTART_DATEField;
    
    private bool sTART_DATEFieldSpecified;
    
    private string? sTART_DATE_TIMEField;
    
    private bool sTART_DATE_TIMEFieldSpecified;
    
    private string? eND_DATEField;
    
    private bool eND_DATEFieldSpecified;
    
    private string? eND_DATE_TIMEField;
    
    private bool eND_DATE_TIMEFieldSpecified;
    
    private string? sTART_DATE_TIME_GMTField;
    
    private bool sTART_DATE_TIME_GMTFieldSpecified;
    
    private string? eND_DATE_TIME_GMTField;
    
    private bool eND_DATE_TIME_GMTFieldSpecified;
    
    private string mKT_START_HEField;
    
    private string sTART_HEField;
    
    private string eND_HEField;
    
    private string rEASONField;
    
    private string nOTESField;
    
    private string sTATUS_TYPEField;
    
    private string cATEGORYField;
    
    private string? pUBLISH_TIMEField;
    
    private bool pUBLISH_TIMEFieldSpecified;
    
    private string? pUBLISH_TIME_GMTField;
    
    private bool pUBLISH_TIME_GMTFieldSpecified;
    
    private System.Nullable<double> cRR_NSRField;
    
    private bool cRR_NSRFieldSpecified;
    
    private string cRR_OPTIONField;
    
    private string cRR_SEGMENTField;
    
    private string? eFF_QTR_START_DTField;
    
    private bool eFF_QTR_START_DTFieldSpecified;
    
    private string? eFF_QTR_END_DTField;
    
    private bool eFF_QTR_END_DTFieldSpecified;
    
    private string? eFF_QTR_START_DT_GMTField;
    
    private bool eFF_QTR_START_DT_GMTFieldSpecified;
    
    private string? eFF_QTR_END_DT_GMTField;
    
    private bool eFF_QTR_END_DT_GMTFieldSpecified;
    
    private string? mKT_RUN_START_TIMEField;
    
    private bool mKT_RUN_START_TIMEFieldSpecified;
    
    private string? mKT_RUN_START_TIME_GMTField;
    
    private bool mKT_RUN_START_TIME_GMTFieldSpecified;
    
    private string? iNT_START_TIMEField;
    
    private bool iNT_START_TIMEFieldSpecified;
    
    private string rEPORT_DATEField;
    
    private bool rEPORT_DATEFieldSpecified;
    
    private string rEPORT_DATE_GMTField;
    
    private bool rEPORT_DATE_GMTFieldSpecified;
    
    private string oUTAGE_DATEField;
    
    private bool oUTAGE_DATEFieldSpecified;
    
    private string oUTAGE_HOURField;
    
    private string tRADING_HUBField;
    
    private string fUEL_CATEGORYField;
    
    private string rENEWABLE_TYPEField;
    
    private string iNT_OPR_HRField;
    
    private string bAA_GRP_IDField;
    
    private string bAA_IDField;
    
    private string iTC_TYPEField;
    
    private string sNAPSHOT_INDICATORField;
    
    private string tIE_NAMEField;
    
    private string cNSTR_TYPEField;
    
    private string pRODUCTField;
    
    private string rAMP_TYPEField;
    
    private string tAC_AREAField;
    
    private System.Nullable<double> fLEX_RAMP_REQ_MWField;
    
    private bool fLEX_RAMP_REQ_MWFieldSpecified;
    
    private System.Nullable<double> nET_DEMAND_MWField;
    
    private bool nET_DEMAND_MWFieldSpecified;
    
    private System.Nullable<double> uNCERTAINTY_MWField;
    
    private bool uNCERTAINTY_MWFieldSpecified;
    
    private System.Nullable<double> sEGMENT_MWField;
    
    private bool sEGMENT_MWFieldSpecified;
    
    private System.Nullable<double> sEGMENT_PRCField;
    
    private bool sEGMENT_PRCFieldSpecified;
    
    private string sCH_CNSTRField;
    
    private string fROM_BAAField;
    
    private string tO_BAAField;
    
    private string gRANULARITYField;
    
    private string? fCST_PUBLICATION_GMTField;
    
    private bool fCST_PUBLICATION_GMTFieldSpecified;
    
    private string cOMPETITIVE_FLAGField;
    
    private System.Nullable<double> cHANGE_IN_LOAD_DEMANDField;
    
    private bool cHANGE_IN_LOAD_DEMANDFieldSpecified;
    
    private System.Nullable<double> dIVERSITY_BENEFIT_UCField;
    
    private bool dIVERSITY_BENEFIT_UCFieldSpecified;
    
    private System.Nullable<double> nET_EXPORT_CAPABILITYField;
    
    private bool nET_EXPORT_CAPABILITYFieldSpecified;
    
    private System.Nullable<double> nET_IMPORT_CAPABILITYField;
    
    private bool nET_IMPORT_CAPABILITYFieldSpecified;
    
    private System.Nullable<double> cREDITField;
    
    private bool cREDITFieldSpecified;
    
    /// <remarks/>
    public OASISDataItems DATA_ITEM {
        get {
            return this.dATA_ITEMField;
        }
        set {
            this.dATA_ITEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SOURCE {
        get {
            return this.sOURCEField;
        }
        set {
            this.sOURCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SINK {
        get {
            return this.sINKField;
        }
        set {
            this.sINKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RESOURCE_NAME {
        get {
            return this.rESOURCE_NAMEField;
        }
        set {
            this.rESOURCE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DIRECTION {
        get {
            return this.dIRECTIONField;
        }
        set {
            this.dIRECTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? OPR_DATE {
        get {
            return this.oPR_DATEField;
        }
        set {
            this.oPR_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OPR_DATESpecified {
        get {
            return this.oPR_DATEFieldSpecified;
        }
        set {
            this.oPR_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? GAS_FLOW_DATE {
        get {
            return this.gAS_FLOW_DATEField;
        }
        set {
            this.gAS_FLOW_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GAS_FLOW_DATESpecified {
        get {
            return this.gAS_FLOW_DATEFieldSpecified;
        }
        set {
            this.gAS_FLOW_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string INTERVAL_NUM {
        get {
            return this.iNTERVAL_NUMField;
        }
        set {
            this.iNTERVAL_NUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INTERVAL_START_GMT {
        get {
            return this.iNTERVAL_START_GMTField;
        }
        set {
            this.iNTERVAL_START_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INTERVAL_START_GMTSpecified {
        get {
            return this.iNTERVAL_START_GMTFieldSpecified;
        }
        set {
            this.iNTERVAL_START_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INTERVAL_END_GMT {
        get {
            return this.iNTERVAL_END_GMTField;
        }
        set {
            this.iNTERVAL_END_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INTERVAL_END_GMTSpecified {
        get {
            return this.iNTERVAL_END_GMTFieldSpecified;
        }
        set {
            this.iNTERVAL_END_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PHYSICAL_TYPE {
        get {
            return this.pHYSICAL_TYPEField;
        }
        set {
            this.pHYSICAL_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> MAXIMUM_LIMIT {
        get {
            return this.mAXIMUM_LIMITField;
        }
        set {
            this.mAXIMUM_LIMITField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MAXIMUM_LIMITSpecified {
        get {
            return this.mAXIMUM_LIMITFieldSpecified;
        }
        set {
            this.mAXIMUM_LIMITFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> MINIMUM_LIMIT {
        get {
            return this.mINIMUM_LIMITField;
        }
        set {
            this.mINIMUM_LIMITField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MINIMUM_LIMITSpecified {
        get {
            return this.mINIMUM_LIMITFieldSpecified;
        }
        set {
            this.mINIMUM_LIMITFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string LIMIT_TYPE {
        get {
            return this.lIMIT_TYPEField;
        }
        set {
            this.lIMIT_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CONSTRAINT_GROUP_NAME {
        get {
            return this.cONSTRAINT_GROUP_NAMEField;
        }
        set {
            this.cONSTRAINT_GROUP_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> VALUE {
        get {
            return this.vALUEField;
        }
        set {
            this.vALUEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VALUESpecified {
        get {
            return this.vALUEFieldSpecified;
        }
        set {
            this.vALUEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SVALUE {
        get {
            return this.sVALUEField;
        }
        set {
            this.sVALUEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OPTION {
        get {
            return this.oPTIONField;
        }
        set {
            this.oPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INVENTORY_DATE_TIME {
        get {
            return this.iNVENTORY_DATE_TIMEField;
        }
        set {
            this.iNVENTORY_DATE_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INVENTORY_DATE_TIMESpecified {
        get {
            return this.iNVENTORY_DATE_TIMEFieldSpecified;
        }
        set {
            this.iNVENTORY_DATE_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INVENTORY_DATE_TIME_GMT {
        get {
            return this.iNVENTORY_DATE_TIME_GMTField;
        }
        set {
            this.iNVENTORY_DATE_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INVENTORY_DATE_TIME_GMTSpecified {
        get {
            return this.iNVENTORY_DATE_TIME_GMTFieldSpecified;
        }
        set {
            this.iNVENTORY_DATE_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? START_DATE {
        get {
            return this.sTART_DATEField;
        }
        set {
            this.sTART_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool START_DATESpecified {
        get {
            return this.sTART_DATEFieldSpecified;
        }
        set {
            this.sTART_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? START_DATE_TIME {
        get {
            return this.sTART_DATE_TIMEField;
        }
        set {
            this.sTART_DATE_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool START_DATE_TIMESpecified {
        get {
            return this.sTART_DATE_TIMEFieldSpecified;
        }
        set {
            this.sTART_DATE_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? END_DATE {
        get {
            return this.eND_DATEField;
        }
        set {
            this.eND_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool END_DATESpecified {
        get {
            return this.eND_DATEFieldSpecified;
        }
        set {
            this.eND_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? END_DATE_TIME {
        get {
            return this.eND_DATE_TIMEField;
        }
        set {
            this.eND_DATE_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool END_DATE_TIMESpecified {
        get {
            return this.eND_DATE_TIMEFieldSpecified;
        }
        set {
            this.eND_DATE_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? START_DATE_TIME_GMT {
        get {
            return this.sTART_DATE_TIME_GMTField;
        }
        set {
            this.sTART_DATE_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool START_DATE_TIME_GMTSpecified {
        get {
            return this.sTART_DATE_TIME_GMTFieldSpecified;
        }
        set {
            this.sTART_DATE_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? END_DATE_TIME_GMT {
        get {
            return this.eND_DATE_TIME_GMTField;
        }
        set {
            this.eND_DATE_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool END_DATE_TIME_GMTSpecified {
        get {
            return this.eND_DATE_TIME_GMTFieldSpecified;
        }
        set {
            this.eND_DATE_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string MKT_START_HE {
        get {
            return this.mKT_START_HEField;
        }
        set {
            this.mKT_START_HEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string START_HE {
        get {
            return this.sTART_HEField;
        }
        set {
            this.sTART_HEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string END_HE {
        get {
            return this.eND_HEField;
        }
        set {
            this.eND_HEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string REASON {
        get {
            return this.rEASONField;
        }
        set {
            this.rEASONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string NOTES {
        get {
            return this.nOTESField;
        }
        set {
            this.nOTESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string STATUS_TYPE {
        get {
            return this.sTATUS_TYPEField;
        }
        set {
            this.sTATUS_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CATEGORY {
        get {
            return this.cATEGORYField;
        }
        set {
            this.cATEGORYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? PUBLISH_TIME {
        get {
            return this.pUBLISH_TIMEField;
        }
        set {
            this.pUBLISH_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PUBLISH_TIMESpecified {
        get {
            return this.pUBLISH_TIMEFieldSpecified;
        }
        set {
            this.pUBLISH_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? PUBLISH_TIME_GMT {
        get {
            return this.pUBLISH_TIME_GMTField;
        }
        set {
            this.pUBLISH_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PUBLISH_TIME_GMTSpecified {
        get {
            return this.pUBLISH_TIME_GMTFieldSpecified;
        }
        set {
            this.pUBLISH_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> CRR_NSR {
        get {
            return this.cRR_NSRField;
        }
        set {
            this.cRR_NSRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CRR_NSRSpecified {
        get {
            return this.cRR_NSRFieldSpecified;
        }
        set {
            this.cRR_NSRFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_OPTION {
        get {
            return this.cRR_OPTIONField;
        }
        set {
            this.cRR_OPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_SEGMENT {
        get {
            return this.cRR_SEGMENTField;
        }
        set {
            this.cRR_SEGMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? EFF_QTR_START_DT {
        get {
            return this.eFF_QTR_START_DTField;
        }
        set {
            this.eFF_QTR_START_DTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EFF_QTR_START_DTSpecified {
        get {
            return this.eFF_QTR_START_DTFieldSpecified;
        }
        set {
            this.eFF_QTR_START_DTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? EFF_QTR_END_DT {
        get {
            return this.eFF_QTR_END_DTField;
        }
        set {
            this.eFF_QTR_END_DTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EFF_QTR_END_DTSpecified {
        get {
            return this.eFF_QTR_END_DTFieldSpecified;
        }
        set {
            this.eFF_QTR_END_DTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? EFF_QTR_START_DT_GMT {
        get {
            return this.eFF_QTR_START_DT_GMTField;
        }
        set {
            this.eFF_QTR_START_DT_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EFF_QTR_START_DT_GMTSpecified {
        get {
            return this.eFF_QTR_START_DT_GMTFieldSpecified;
        }
        set {
            this.eFF_QTR_START_DT_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? EFF_QTR_END_DT_GMT {
        get {
            return this.eFF_QTR_END_DT_GMTField;
        }
        set {
            this.eFF_QTR_END_DT_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EFF_QTR_END_DT_GMTSpecified {
        get {
            return this.eFF_QTR_END_DT_GMTFieldSpecified;
        }
        set {
            this.eFF_QTR_END_DT_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MKT_RUN_START_TIME {
        get {
            return this.mKT_RUN_START_TIMEField;
        }
        set {
            this.mKT_RUN_START_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MKT_RUN_START_TIMESpecified {
        get {
            return this.mKT_RUN_START_TIMEFieldSpecified;
        }
        set {
            this.mKT_RUN_START_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MKT_RUN_START_TIME_GMT {
        get {
            return this.mKT_RUN_START_TIME_GMTField;
        }
        set {
            this.mKT_RUN_START_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MKT_RUN_START_TIME_GMTSpecified {
        get {
            return this.mKT_RUN_START_TIME_GMTFieldSpecified;
        }
        set {
            this.mKT_RUN_START_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INT_START_TIME {
        get {
            return this.iNT_START_TIMEField;
        }
        set {
            this.iNT_START_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INT_START_TIMESpecified {
        get {
            return this.iNT_START_TIMEFieldSpecified;
        }
        set {
            this.iNT_START_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute()]
    public string REPORT_DATE {
        get {
            return this.rEPORT_DATEField;
        }
        set {
            this.rEPORT_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool REPORT_DATESpecified {
        get {
            return this.rEPORT_DATEFieldSpecified;
        }
        set {
            this.rEPORT_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string REPORT_DATE_GMT {
        get {
            return this.rEPORT_DATE_GMTField;
        }
        set {
            this.rEPORT_DATE_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool REPORT_DATE_GMTSpecified {
        get {
            return this.rEPORT_DATE_GMTFieldSpecified;
        }
        set {
            this.rEPORT_DATE_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute()]
    public string OUTAGE_DATE {
        get {
            return this.oUTAGE_DATEField;
        }
        set {
            this.oUTAGE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OUTAGE_DATESpecified {
        get {
            return this.oUTAGE_DATEFieldSpecified;
        }
        set {
            this.oUTAGE_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string OUTAGE_HOUR {
        get {
            return this.oUTAGE_HOURField;
        }
        set {
            this.oUTAGE_HOURField = value;
        }
    }
    
    /// <remarks/>
    public string TRADING_HUB {
        get {
            return this.tRADING_HUBField;
        }
        set {
            this.tRADING_HUBField = value;
        }
    }
    
    /// <remarks/>
    public string FUEL_CATEGORY {
        get {
            return this.fUEL_CATEGORYField;
        }
        set {
            this.fUEL_CATEGORYField = value;
        }
    }
    
    /// <remarks/>
    public string RENEWABLE_TYPE {
        get {
            return this.rENEWABLE_TYPEField;
        }
        set {
            this.rENEWABLE_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string INT_OPR_HR {
        get {
            return this.iNT_OPR_HRField;
        }
        set {
            this.iNT_OPR_HRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BAA_GRP_ID {
        get {
            return this.bAA_GRP_IDField;
        }
        set {
            this.bAA_GRP_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BAA_ID {
        get {
            return this.bAA_IDField;
        }
        set {
            this.bAA_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ITC_TYPE {
        get {
            return this.iTC_TYPEField;
        }
        set {
            this.iTC_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SNAPSHOT_INDICATOR {
        get {
            return this.sNAPSHOT_INDICATORField;
        }
        set {
            this.sNAPSHOT_INDICATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TIE_NAME {
        get {
            return this.tIE_NAMEField;
        }
        set {
            this.tIE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CNSTR_TYPE {
        get {
            return this.cNSTR_TYPEField;
        }
        set {
            this.cNSTR_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PRODUCT {
        get {
            return this.pRODUCTField;
        }
        set {
            this.pRODUCTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RAMP_TYPE {
        get {
            return this.rAMP_TYPEField;
        }
        set {
            this.rAMP_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TAC_AREA {
        get {
            return this.tAC_AREAField;
        }
        set {
            this.tAC_AREAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> FLEX_RAMP_REQ_MW {
        get {
            return this.fLEX_RAMP_REQ_MWField;
        }
        set {
            this.fLEX_RAMP_REQ_MWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FLEX_RAMP_REQ_MWSpecified {
        get {
            return this.fLEX_RAMP_REQ_MWFieldSpecified;
        }
        set {
            this.fLEX_RAMP_REQ_MWFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> NET_DEMAND_MW {
        get {
            return this.nET_DEMAND_MWField;
        }
        set {
            this.nET_DEMAND_MWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NET_DEMAND_MWSpecified {
        get {
            return this.nET_DEMAND_MWFieldSpecified;
        }
        set {
            this.nET_DEMAND_MWFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> UNCERTAINTY_MW {
        get {
            return this.uNCERTAINTY_MWField;
        }
        set {
            this.uNCERTAINTY_MWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UNCERTAINTY_MWSpecified {
        get {
            return this.uNCERTAINTY_MWFieldSpecified;
        }
        set {
            this.uNCERTAINTY_MWFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> SEGMENT_MW {
        get {
            return this.sEGMENT_MWField;
        }
        set {
            this.sEGMENT_MWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SEGMENT_MWSpecified {
        get {
            return this.sEGMENT_MWFieldSpecified;
        }
        set {
            this.sEGMENT_MWFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> SEGMENT_PRC {
        get {
            return this.sEGMENT_PRCField;
        }
        set {
            this.sEGMENT_PRCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SEGMENT_PRCSpecified {
        get {
            return this.sEGMENT_PRCFieldSpecified;
        }
        set {
            this.sEGMENT_PRCFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SCH_CNSTR {
        get {
            return this.sCH_CNSTRField;
        }
        set {
            this.sCH_CNSTRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FROM_BAA {
        get {
            return this.fROM_BAAField;
        }
        set {
            this.fROM_BAAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TO_BAA {
        get {
            return this.tO_BAAField;
        }
        set {
            this.tO_BAAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GRANULARITY {
        get {
            return this.gRANULARITYField;
        }
        set {
            this.gRANULARITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? FCST_PUBLICATION_GMT {
        get {
            return this.fCST_PUBLICATION_GMTField;
        }
        set {
            this.fCST_PUBLICATION_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FCST_PUBLICATION_GMTSpecified {
        get {
            return this.fCST_PUBLICATION_GMTFieldSpecified;
        }
        set {
            this.fCST_PUBLICATION_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string COMPETITIVE_FLAG {
        get {
            return this.cOMPETITIVE_FLAGField;
        }
        set {
            this.cOMPETITIVE_FLAGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> CHANGE_IN_LOAD_DEMAND {
        get {
            return this.cHANGE_IN_LOAD_DEMANDField;
        }
        set {
            this.cHANGE_IN_LOAD_DEMANDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CHANGE_IN_LOAD_DEMANDSpecified {
        get {
            return this.cHANGE_IN_LOAD_DEMANDFieldSpecified;
        }
        set {
            this.cHANGE_IN_LOAD_DEMANDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> DIVERSITY_BENEFIT_UC {
        get {
            return this.dIVERSITY_BENEFIT_UCField;
        }
        set {
            this.dIVERSITY_BENEFIT_UCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DIVERSITY_BENEFIT_UCSpecified {
        get {
            return this.dIVERSITY_BENEFIT_UCFieldSpecified;
        }
        set {
            this.dIVERSITY_BENEFIT_UCFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> NET_EXPORT_CAPABILITY {
        get {
            return this.nET_EXPORT_CAPABILITYField;
        }
        set {
            this.nET_EXPORT_CAPABILITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NET_EXPORT_CAPABILITYSpecified {
        get {
            return this.nET_EXPORT_CAPABILITYFieldSpecified;
        }
        set {
            this.nET_EXPORT_CAPABILITYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> NET_IMPORT_CAPABILITY {
        get {
            return this.nET_IMPORT_CAPABILITYField;
        }
        set {
            this.nET_IMPORT_CAPABILITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NET_IMPORT_CAPABILITYSpecified {
        get {
            return this.nET_IMPORT_CAPABILITYFieldSpecified;
        }
        set {
            this.nET_IMPORT_CAPABILITYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> CREDIT {
        get {
            return this.cREDITField;
        }
        set {
            this.cREDITField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CREDITSpecified {
        get {
            return this.cREDITFieldSpecified;
        }
        set {
            this.cREDITFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum OASISDataItems {
    
    /// <remarks/>
    NS_REQ_MAX_MW,
    
    /// <remarks/>
    RD_REQ_MAX_MW,
    
    /// <remarks/>
    RU_REQ_MAX_MW,
    
    /// <remarks/>
    SP_REQ_MAX_MW,
    
    /// <remarks/>
    RMD_REQ_MAX_MW,
    
    /// <remarks/>
    RMU_REQ_MAX_MW,
    
    /// <remarks/>
    NS_REQ_MIN_MW,
    
    /// <remarks/>
    RD_REQ_MIN_MW,
    
    /// <remarks/>
    RU_REQ_MIN_MW,
    
    /// <remarks/>
    SP_REQ_MIN_MW,
    
    /// <remarks/>
    RMD_REQ_MIN_MW,
    
    /// <remarks/>
    RMU_REQ_MIN_MW,
    
    /// <remarks/>
    AS_REQ_MAX_MW,
    
    /// <remarks/>
    AS_REQ_MIN_MW,
    
    /// <remarks/>
    TOT_GEN_MW,
    
    /// <remarks/>
    TOT_LOAD_MW,
    
    /// <remarks/>
    TOT_IMP_MW,
    
    /// <remarks/>
    TOT_EXP_MW,
    
    /// <remarks/>
    ISO_TOT_GEN_MW,
    
    /// <remarks/>
    ISO_TOT_LOAD_MW,
    
    /// <remarks/>
    ISO_TOT_IMP_MW,
    
    /// <remarks/>
    ISO_TOT_EXP_MW,
    
    /// <remarks/>
    ISO_TOTAL_MWH,
    
    /// <remarks/>
    DASE_MWH,
    
    /// <remarks/>
    DSSE_MWH,
    
    /// <remarks/>
    DABE_MWH,
    
    /// <remarks/>
    DAPE_MWH,
    
    /// <remarks/>
    OE_MWH,
    
    /// <remarks/>
    HASE_MWH,
    
    /// <remarks/>
    SRE_MWH,
    
    /// <remarks/>
    RED_MWH,
    
    /// <remarks/>
    EDE_MWH,
    
    /// <remarks/>
    RMRE_MWH,
    
    /// <remarks/>
    MSSLFE_MWH,
    
    /// <remarks/>
    RE_MWH,
    
    /// <remarks/>
    RIE_MWH,
    
    /// <remarks/>
    MLE_MWH,
    
    /// <remarks/>
    SE_MWH,
    
    /// <remarks/>
    DRE_MWH,
    
    /// <remarks/>
    RTSSE_MWH,
    
    /// <remarks/>
    DMLE_MWH,
    
    /// <remarks/>
    DAMLE_MWH,
    
    /// <remarks/>
    PE_MWH,
    
    /// <remarks/>
    TEE_MWH,
    
    /// <remarks/>
    LFE_MWH,
    
    /// <remarks/>
    SYSEMR_MWH,
    
    /// <remarks/>
    RMRR_MWH,
    
    /// <remarks/>
    RMRS_MWH,
    
    /// <remarks/>
    RMRT_MWH,
    
    /// <remarks/>
    BS_MWH,
    
    /// <remarks/>
    VS_MWH,
    
    /// <remarks/>
    SLIC_MWH,
    
    /// <remarks/>
    TORETC_MWH,
    
    /// <remarks/>
    TEMR_MWH,
    
    /// <remarks/>
    TMODEL_MWH,
    
    /// <remarks/>
    TMODEL1_MWH,
    
    /// <remarks/>
    TMODEL2_MWH,
    
    /// <remarks/>
    TMODEL3_MWH,
    
    /// <remarks/>
    TMODEL4_MWH,
    
    /// <remarks/>
    TMODEL5_MWH,
    
    /// <remarks/>
    TMODEL6_MWH,
    
    /// <remarks/>
    TMODEL7_MWH,
    
    /// <remarks/>
    RMRC2_MWH,
    
    /// <remarks/>
    RMRRC2_MWH,
    
    /// <remarks/>
    SYSEMR1_MWH,
    
    /// <remarks/>
    SYSEMR2_MWH,
    
    /// <remarks/>
    TORETC1_MWH,
    
    /// <remarks/>
    OTHER_MWH,
    
    /// <remarks/>
    OTHERS_MWH,
    
    /// <remarks/>
    NONTMOD_MWH,
    
    /// <remarks/>
    ASTEST_MWH,
    
    /// <remarks/>
    PRETEST_MWH,
    
    /// <remarks/>
    LMP_CONG_PRC,
    
    /// <remarks/>
    LMP_CONG_CC_PRC,
    
    /// <remarks/>
    LMP_CONG_NC_PRC,
    
    /// <remarks/>
    LMP_ENE_PRC,
    
    /// <remarks/>
    LMP_LOSS_PRC,
    
    /// <remarks/>
    LMP_PRC,
    
    /// <remarks/>
    SYS_FCST_DA_MW,
    
    /// <remarks/>
    SYS_FCST_2DA_MW,
    
    /// <remarks/>
    SYS_FCST_ACT_MW,
    
    /// <remarks/>
    SYS_FCST_5MIN_MW,
    
    /// <remarks/>
    SYS_FCST_15MIN_MW,
    
    /// <remarks/>
    SYS_PEAK_MW,
    
    /// <remarks/>
    ATC_MW,
    
    /// <remarks/>
    AS_IMPORT_MW,
    
    /// <remarks/>
    ENE_IMPORT_MW,
    
    /// <remarks/>
    CBM_MW,
    
    /// <remarks/>
    OTC_MW,
    
    /// <remarks/>
    TTC_MW,
    
    /// <remarks/>
    CONSTRAINT_MW,
    
    /// <remarks/>
    ENTLEMTS_MW,
    
    /// <remarks/>
    USEAGE_MW,
    
    /// <remarks/>
    OUTAGE_LIMIT_MW,
    
    /// <remarks/>
    ST_ON_PRC,
    
    /// <remarks/>
    ST_OFF_PRC,
    
    /// <remarks/>
    LT_ON_PRC,
    
    /// <remarks/>
    LT_OFF_PRC,
    
    /// <remarks/>
    ON_PRC,
    
    /// <remarks/>
    OFF_PRC,
    
    /// <remarks/>
    OP_RSRV_ACT_PCT,
    
    /// <remarks/>
    NS_CLR_PRC,
    
    /// <remarks/>
    RD_CLR_PRC,
    
    /// <remarks/>
    RU_CLR_PRC,
    
    /// <remarks/>
    SP_CLR_PRC,
    
    /// <remarks/>
    RMD_CLR_PRC,
    
    /// <remarks/>
    RMU_CLR_PRC,
    
    /// <remarks/>
    SHADOW_PRC,
    
    /// <remarks/>
    NS_PROC_MW,
    
    /// <remarks/>
    NS_SPROC_MW,
    
    /// <remarks/>
    NS_TOT_MW,
    
    /// <remarks/>
    NS_IMP_MW,
    
    /// <remarks/>
    NS_GEN_MW,
    
    /// <remarks/>
    NS_DMD_MW,
    
    /// <remarks/>
    NS_TOT_CST_PRC,
    
    /// <remarks/>
    ISO_TOT_CST_PRC,
    
    /// <remarks/>
    NS_ISO_TOT_CST_PRC,
    
    /// <remarks/>
    NS_AVG_ASMP_PRC,
    
    /// <remarks/>
    NS_ISO_AVG_ASMP_PRC,
    
    /// <remarks/>
    SP_PROC_MW,
    
    /// <remarks/>
    SP_SPROC_MW,
    
    /// <remarks/>
    SP_TOT_MW,
    
    /// <remarks/>
    SP_IMP_MW,
    
    /// <remarks/>
    SP_GEN_MW,
    
    /// <remarks/>
    SP_DMD_MW,
    
    /// <remarks/>
    SP_TOT_CST_PRC,
    
    /// <remarks/>
    SP_AVG_ASMP_PRC,
    
    /// <remarks/>
    SP_ISO_TOT_CST_PRC,
    
    /// <remarks/>
    SP_ISO_AVG_ASMP_PRC,
    
    /// <remarks/>
    RU_PROC_MW,
    
    /// <remarks/>
    RU_SPROC_MW,
    
    /// <remarks/>
    RU_TOT_MW,
    
    /// <remarks/>
    RU_IMP_MW,
    
    /// <remarks/>
    RU_GEN_MW,
    
    /// <remarks/>
    RU_DMD_MW,
    
    /// <remarks/>
    RU_TOT_CST_PRC,
    
    /// <remarks/>
    RU_AVG_ASMP_PRC,
    
    /// <remarks/>
    RU_ISO_TOT_CST_PRC,
    
    /// <remarks/>
    RU_ISO_AVG_ASMP_PRC,
    
    /// <remarks/>
    RD_PROC_MW,
    
    /// <remarks/>
    RD_SPROC_MW,
    
    /// <remarks/>
    RD_TOT_MW,
    
    /// <remarks/>
    RD_IMP_MW,
    
    /// <remarks/>
    RD_GEN_MW,
    
    /// <remarks/>
    RD_DMD_MW,
    
    /// <remarks/>
    RD_TOT_CST_PRC,
    
    /// <remarks/>
    RD_AVG_ASMP_PRC,
    
    /// <remarks/>
    RD_ISO_TOT_CST_PRC,
    
    /// <remarks/>
    RD_ISO_AVG_ASMP_PRC,
    
    /// <remarks/>
    RMD_PROC_MW,
    
    /// <remarks/>
    RMD_SPROC_MW,
    
    /// <remarks/>
    RMD_TOT_MW,
    
    /// <remarks/>
    RMD_TOT_CST_PRC,
    
    /// <remarks/>
    RMU_PROC_MW,
    
    /// <remarks/>
    RMU_SPROC_MW,
    
    /// <remarks/>
    RMU_TOT_MW,
    
    /// <remarks/>
    RMU_TOT_CST_PRC,
    
    /// <remarks/>
    FUEL_PRC,
    
    /// <remarks/>
    TOT_CAP_USED_MW,
    
    /// <remarks/>
    DISPATCH_MW,
    
    /// <remarks/>
    TOT_AVAIL_MW,
    
    /// <remarks/>
    DETER_MW,
    
    /// <remarks/>
    RA_CAP_COMM_MW,
    
    /// <remarks/>
    MIN_LD_MW,
    
    /// <remarks/>
    RA_MLC_PRC,
    
    /// <remarks/>
    MIN_LD_MLC_PRC,
    
    /// <remarks/>
    TOT_STRT_CST_PRC,
    
    /// <remarks/>
    RA_STRT_PRC,
    
    /// <remarks/>
    RA_COMM_UNITS_CNT,
    
    /// <remarks/>
    TOT_COMM_UNITS_CNT,
    
    /// <remarks/>
    TOT_COMM_CAP_MW,
    
    /// <remarks/>
    TOT_LOSS_PRC,
    
    /// <remarks/>
    TOT_LOSS_MW,
    
    /// <remarks/>
    MPM_STATUS_FLG,
    
    /// <remarks/>
    MPM_CMP_STATUS_FLG,
    
    /// <remarks/>
    EXPT_DIS_PRC,
    
    /// <remarks/>
    EXPT_DIS_MWH,
    
    /// <remarks/>
    AS_CLEAR_ASMP_RTM,
    
    /// <remarks/>
    AS_CLEAR_COST_IFM,
    
    /// <remarks/>
    AS_CLEAR_COST_RTM,
    
    /// <remarks/>
    AS_CLEAR_MW_IFM,
    
    /// <remarks/>
    AS_CLEAR_MW_RTM,
    
    /// <remarks/>
    AS_GEN_TOTAL_MW_IFM,
    
    /// <remarks/>
    AS_GEN_TOTAL_MW_RTM,
    
    /// <remarks/>
    AS_IMP_TOTAL_MW_IFM,
    
    /// <remarks/>
    AS_IMP_TOTAL_MW_RTM,
    
    /// <remarks/>
    AS_LOAD_TOTAL_MW_IFM,
    
    /// <remarks/>
    AS_LOAD_TOTAL_MW_RTM,
    
    /// <remarks/>
    AS_REGION_value,
    
    /// <remarks/>
    AS_REGION_REQ_MAX,
    
    /// <remarks/>
    AS_REGION_REQ_MIN,
    
    /// <remarks/>
    AS_SELF_MW_IFM,
    
    /// <remarks/>
    AS_SELF_MW_RTM,
    
    /// <remarks/>
    AS_TOTAL_MW,
    
    /// <remarks/>
    AS_TOTAL_MW_IFM,
    
    /// <remarks/>
    AS_TOTAL_MW_RTM,
    
    /// <remarks/>
    AS_TYPE,
    
    /// <remarks/>
    AS_USER_RATE,
    
    /// <remarks/>
    CA_value,
    
    /// <remarks/>
    CMMT_MINLOAD_MLC,
    
    /// <remarks/>
    CMMT_TOTAL_MINLOAD_MLC,
    
    /// <remarks/>
    CMMT_TOTAL_RA_MINLOAD_MLC,
    
    /// <remarks/>
    CMMT_MINLOAD_MW,
    
    /// <remarks/>
    CMMT_RA_MLC,
    
    /// <remarks/>
    CMMT_RA_MINLOAD_MW,
    
    /// <remarks/>
    CMMT_RA_TOTAL_MINLOAD_MW,
    
    /// <remarks/>
    CMMT_TOTAL_MINLOAD_MW,
    
    /// <remarks/>
    CMMT_RA_MINLOAD_MLC,
    
    /// <remarks/>
    CMMT_START_COST,
    
    /// <remarks/>
    CMMT_RA_START_COST,
    
    /// <remarks/>
    CMMT_TOTAL_START_COST,
    
    /// <remarks/>
    CMMT_RA_TOTAL_START_COST,
    
    /// <remarks/>
    CMMT_RA_UNITS,
    
    /// <remarks/>
    CMMT_UNITS,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CMMT_TOTAL_START_COST")]
    CMMT_TOTAL_START_COST1,
    
    /// <remarks/>
    CMMT_TOTAL_MW,
    
    /// <remarks/>
    CMMT_TOTAL_UNITS,
    
    /// <remarks/>
    CMMT_RA_TOTAL_UNITS,
    
    /// <remarks/>
    CMMT_CAP_MW,
    
    /// <remarks/>
    CMMT_TOTAL_CAP_MW,
    
    /// <remarks/>
    CMMT_RA_TOTAL_CAP_MW,
    
    /// <remarks/>
    CMMT_RA_CAP_MW,
    
    /// <remarks/>
    CRR_CAT,
    
    /// <remarks/>
    CRR_ID,
    
    /// <remarks/>
    CRR_MARKET_value,
    
    /// <remarks/>
    CRR_MW,
    
    /// <remarks/>
    CRR_NSR,
    
    /// <remarks/>
    CRR_MARKET_TERM,
    
    /// <remarks/>
    CRR_OPTION,
    
    /// <remarks/>
    CRR_OWNER,
    
    /// <remarks/>
    CRR_SEGMENT,
    
    /// <remarks/>
    CRR_TERM,
    
    /// <remarks/>
    CRR_TOU,
    
    /// <remarks/>
    CRR_TYPE,
    
    /// <remarks/>
    ENE_EA_DA,
    
    /// <remarks/>
    ENE_EA_EXCEPT,
    
    /// <remarks/>
    ENE_EA_HASP,
    
    /// <remarks/>
    ENE_EA_MLE,
    
    /// <remarks/>
    ENE_EA_MSSLF,
    
    /// <remarks/>
    ENE_EA_OPTIMAL,
    
    /// <remarks/>
    ENE_EA_RAMP_DEV,
    
    /// <remarks/>
    ENE_EA_RAMP_STD,
    
    /// <remarks/>
    ENE_EA_RESIDUAL,
    
    /// <remarks/>
    ENE_EA_RMR,
    
    /// <remarks/>
    ENE_EA_SELF,
    
    /// <remarks/>
    ENE_EA_SLIC,
    
    /// <remarks/>
    ENE_EXP_CLEAR_HASP,
    
    /// <remarks/>
    ENE_EXP_CLEAR_IFM,
    
    /// <remarks/>
    ENE_EXP_CLEAR_RTM,
    
    /// <remarks/>
    ENE_GEN_CLEAR_HASP,
    
    /// <remarks/>
    ENE_GEN_CLEAR_IFM,
    
    /// <remarks/>
    ENE_GEN_CLEAR_RTM,
    
    /// <remarks/>
    ENE_IMP_CLEAR_HASP,
    
    /// <remarks/>
    ENE_IMP_CLEAR_IFM,
    
    /// <remarks/>
    ENE_IMP_CLEAR_RTM,
    
    /// <remarks/>
    ENE_LOAD_ACTUAL,
    
    /// <remarks/>
    ENE_LOAD_CLEAR_HASP,
    
    /// <remarks/>
    ENE_LOAD_CLEAR_IFM,
    
    /// <remarks/>
    ENE_LOAD_CLEAR_RTM,
    
    /// <remarks/>
    ENE_LOAD_FCST,
    
    /// <remarks/>
    ENE_PEAK_HOUR,
    
    /// <remarks/>
    ENE_PEAK_LOAD,
    
    /// <remarks/>
    FUEL_REGION_value,
    
    /// <remarks/>
    INVT_DATETIME,
    
    /// <remarks/>
    LOAD_ACTUAL,
    
    /// <remarks/>
    LOAD_CLEAR_RTM,
    
    /// <remarks/>
    LOSS_TOTAL_COST_HASP,
    
    /// <remarks/>
    LOSS_TOTAL_COST_RTM,
    
    /// <remarks/>
    LOSS_TOTAL_MW_HASP,
    
    /// <remarks/>
    LOSS_TOTAL_MW_RTM,
    
    /// <remarks/>
    MPM_FLAG,
    
    /// <remarks/>
    OP_RSRV_TOTAL,
    
    /// <remarks/>
    PRC_NG,
    
    /// <remarks/>
    PRC_SHADOW,
    
    /// <remarks/>
    RMR_DETER_DAM,
    
    /// <remarks/>
    RMR_DETER_HASP,
    
    /// <remarks/>
    RMR_DISPATCH_DAM,
    
    /// <remarks/>
    RMR_DISPATCH_HASP,
    
    /// <remarks/>
    RMR_TOTAL,
    
    /// <remarks/>
    RMR_TOTAL_AVAIL,
    
    /// <remarks/>
    RUC_GEN_CLEAR_RUC,
    
    /// <remarks/>
    RUC_IMP_CLEAR_RUC,
    
    /// <remarks/>
    RUC_LOAD_CLEAR_RUC,
    
    /// <remarks/>
    RUC_ZONE_value,
    
    /// <remarks/>
    TAC_AREA_value,
    
    /// <remarks/>
    TINTRFCE_value,
    
    /// <remarks/>
    TRNS_AS_IMPORT,
    
    /// <remarks/>
    TRNS_ENE_IMPORT,
    
    /// <remarks/>
    TRNS_EQUIP_value,
    
    /// <remarks/>
    TRNS_RATING_CBM,
    
    /// <remarks/>
    TRNS_RATING_DIRECTION,
    
    /// <remarks/>
    TRNS_RATING_OTC,
    
    /// <remarks/>
    TRNS_RATING_OTC_DERATE,
    
    /// <remarks/>
    TRNS_RATING_TTC,
    
    /// <remarks/>
    TRNS_TI_value,
    
    /// <remarks/>
    TRNS_TR_ENTMTS,
    
    /// <remarks/>
    TRNS_TR_USEAGE,
    
    /// <remarks/>
    ATL_PEAK_ON_OFF_FLG,
    
    /// <remarks/>
    SPLY_PRC,
    
    /// <remarks/>
    DMD_PRC,
    
    /// <remarks/>
    ISO_TOT_SPLY_MW,
    
    /// <remarks/>
    ISO_TOT_DMD_MW,
    
    /// <remarks/>
    ENE_CB_CLR_MW,
    
    /// <remarks/>
    DMD_SLF_ENE_SUB_MW,
    
    /// <remarks/>
    DMD_SLF_ENE_CLR_MW,
    
    /// <remarks/>
    DMD_SLF_CLR_CST,
    
    /// <remarks/>
    DMD_ENE_SUB_MW,
    
    /// <remarks/>
    DMD_ENE_SUB_CST,
    
    /// <remarks/>
    DMD_ENE_CLR_MW,
    
    /// <remarks/>
    DMD_ENE_CLR_CST,
    
    /// <remarks/>
    DMD_VIR_ENE_SUB_MW,
    
    /// <remarks/>
    DMD_VIR_SUB_CST,
    
    /// <remarks/>
    DMD_VIR_ENE_CLR_MW,
    
    /// <remarks/>
    DMD_VIR_CLR_CST,
    
    /// <remarks/>
    DMD_TOT_ENE_SUB_MW,
    
    /// <remarks/>
    DMD_TOT_SUB_CST,
    
    /// <remarks/>
    DMD_TOT_ENE_CLR_MW,
    
    /// <remarks/>
    DMD_TOT_CLR_CST,
    
    /// <remarks/>
    SPLY_SLF_ENE_SUB_MW,
    
    /// <remarks/>
    SPLY_SLF_ENE_CLR_MW,
    
    /// <remarks/>
    SPLY_SLF_CLR_CST,
    
    /// <remarks/>
    SPLY_ENE_SUB_MW,
    
    /// <remarks/>
    SPLY_ENE_SUB_CST,
    
    /// <remarks/>
    SPLY_ENE_CLR_MW,
    
    /// <remarks/>
    SPLY_ENE_CLR_CST,
    
    /// <remarks/>
    SPLY_VIR_ENE_SUB_MW,
    
    /// <remarks/>
    SPLY_VIR_SUB_CST,
    
    /// <remarks/>
    SPLY_VIR_ENE_CLR_MW,
    
    /// <remarks/>
    SPLY_VIR_CLR_CST,
    
    /// <remarks/>
    SPLY_TOT_ENE_SUB_MW,
    
    /// <remarks/>
    SPLY_TOT_SUB_CST,
    
    /// <remarks/>
    SPLY_TOT_ENE_CLR_MW,
    
    /// <remarks/>
    SPLY_TOT_CLR_CST,
    
    /// <remarks/>
    EXP_SLF_ENE_SUB_MW,
    
    /// <remarks/>
    EXP_SLF_ENE_CLR_MW,
    
    /// <remarks/>
    EXP_SLF_CLR_CST,
    
    /// <remarks/>
    EXP_ENE_SUB_MW,
    
    /// <remarks/>
    EXP_ENE_SUB_CST,
    
    /// <remarks/>
    EXP_ENE_CLR_MW,
    
    /// <remarks/>
    EXP_ENE_CLR_CST,
    
    /// <remarks/>
    EXP_VIR_ENE_SUB_MW,
    
    /// <remarks/>
    EXP_VIR_SUB_CST,
    
    /// <remarks/>
    EXP_VIR_ENE_CLR_MW,
    
    /// <remarks/>
    EXP_VIR_CLR_CST,
    
    /// <remarks/>
    EXP_TOT_ENE_SUB_MW,
    
    /// <remarks/>
    EXP_TOT_SUB_CST,
    
    /// <remarks/>
    EXP_TOT_ENE_CLR_MW,
    
    /// <remarks/>
    EXP_TOT_CLR_CST,
    
    /// <remarks/>
    IMP_SLF_ENE_SUB_MW,
    
    /// <remarks/>
    IMP_SLF_ENE_CLR_MW,
    
    /// <remarks/>
    IMP_SLF_CLR_CST,
    
    /// <remarks/>
    IMP_ENE_SUB_MW,
    
    /// <remarks/>
    IMP_ENE_SUB_CST,
    
    /// <remarks/>
    IMP_ENE_CLR_MW,
    
    /// <remarks/>
    IMP_ENE_CLR_CST,
    
    /// <remarks/>
    IMP_VIR_ENE_SUB_MW,
    
    /// <remarks/>
    IMP_VIR_SUB_CST,
    
    /// <remarks/>
    IMP_VIR_ENE_CLR_MW,
    
    /// <remarks/>
    IMP_VIR_CLR_CST,
    
    /// <remarks/>
    IMP_TOT_ENE_SUB_MW,
    
    /// <remarks/>
    IMP_TOT_SUB_CST,
    
    /// <remarks/>
    IMP_TOT_ENE_CLR_MW,
    
    /// <remarks/>
    IMP_TOT_CLR_CST,
    
    /// <remarks/>
    DEMAND_REF_PRICE,
    
    /// <remarks/>
    SUPPLY_REF_PRICE,
    
    /// <remarks/>
    EFF_QTR_START_DT,
    
    /// <remarks/>
    EFF_QTR_END_DT,
    
    /// <remarks/>
    CLEARED_MW,
    
    /// <remarks/>
    CB_NODAL_GRP_CNSTR_PRC,
    
    /// <remarks/>
    CB_NODAL_LIMITS,
    
    /// <remarks/>
    INT_START_HR,
    
    /// <remarks/>
    MKT_RUN_ID,
    
    /// <remarks/>
    RAMP_UP_CAP_REQ,
    
    /// <remarks/>
    RAMP_UP_SHADOW_PRC,
    
    /// <remarks/>
    RAMP_DOWN_CAP_REQ,
    
    /// <remarks/>
    RAMP_DOWN_SHADOW_PRC,
    
    /// <remarks/>
    OPR_HR,
    
    /// <remarks/>
    REFERENCE_BUS_ID,
    
    /// <remarks/>
    RENEW_FCST_DA_MW,
    
    /// <remarks/>
    RENEW_FCST_HASP_MW,
    
    /// <remarks/>
    RENEW_FCST_ACT_MW,
    
    /// <remarks/>
    RENEW_FCST_5MIN_MW,
    
    /// <remarks/>
    RENEW_FCST_15MIN_MW,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("OUTAGE MW")]
    OUTAGEMW,
    
    /// <remarks/>
    GHG_ALLOWANCE_PRC,
    
    /// <remarks/>
    TRM_MW,
    
    /// <remarks/>
    TRM_UF_MW,
    
    /// <remarks/>
    TRM_FTO_MW,
    
    /// <remarks/>
    TRM_SPI_MW,
    
    /// <remarks/>
    SYS_FCST_7DA_MW,
    
    /// <remarks/>
    RMD_AVG_MIL,
    
    /// <remarks/>
    RMD_SYS_MIL_MUL,
    
    /// <remarks/>
    RMD_SYS_PERF_ACC,
    
    /// <remarks/>
    RMU_AVG_MIL,
    
    /// <remarks/>
    RMU_SYS_MIL_MUL,
    
    /// <remarks/>
    RMU_SYS_PERF_ACC,
    
    /// <remarks/>
    MKT_XFER_CAP_MW,
    
    /// <remarks/>
    EIM_XFER_MW,
    
    /// <remarks/>
    EIM_DYN_NSI_MW,
    
    /// <remarks/>
    BASE_NSI_MW,
    
    /// <remarks/>
    LMP_GHG_PRC,
    
    /// <remarks/>
    BASE_MWH,
    
    /// <remarks/>
    MDE_MWH,
    
    /// <remarks/>
    SYS_ADV_FCST_MW,
    
    /// <remarks/>
    HRLY_BASE_NSI_MW,
    
    /// <remarks/>
    HRLY_BASE_LOSS_MW,
    
    /// <remarks/>
    UNCERTAINTY_MV_MW,
    
    /// <remarks/>
    AGGR_FLEX_RAMP_MW,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("EIM_XFER_MW")]
    EIM_XFER_MW1,
    
    /// <remarks/>
    FCST_MW,
    
    /// <remarks/>
    MPM_DEFAULT_CMP,
    
    /// <remarks/>
    EIM_XFER_LIMITS_TIE_MW,
    
    /// <remarks/>
    DAM_SCHEDULE,
    
    /// <remarks/>
    DAM_NET_VIRTUAL,
    
    /// <remarks/>
    DAM_FORECAST,
    
    /// <remarks/>
    RTM_SCHEDULE,
    
    /// <remarks/>
    TEST_INDICATOR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class REPORT_HEADEROASIS {
    
    private SystemType sYSTEMField;
    
    private TimeZoneType tzField;
    
    private OASISReportType rEPORTField;
    
    private System.Nullable<OASISMarketType> mKT_TYPEField;
    
    private bool mKT_TYPEFieldSpecified;
    
    private System.Nullable<OASISMarketType> eXECUTION_TYPEField;
    
    private bool eXECUTION_TYPEFieldSpecified;
    
    private string cRR_MKT_NAMEField;
    
    private System.Nullable<UOMType> uOMField;
    
    private bool uOMFieldSpecified;
    
    private OASISIntervalType iNTERVALField;
    
    private bool iNTERVALFieldSpecified;
    
    private string sEC_PER_INTERVALField;
    
    /// <remarks/>
    public SystemType SYSTEM {
        get {
            return this.sYSTEMField;
        }
        set {
            this.sYSTEMField = value;
        }
    }
    
    /// <remarks/>
    public TimeZoneType TZ {
        get {
            return this.tzField;
        }
        set {
            this.tzField = value;
        }
    }
    
    /// <remarks/>
    public OASISReportType REPORT {
        get {
            return this.rEPORTField;
        }
        set {
            this.rEPORTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<OASISMarketType> MKT_TYPE {
        get {
            return this.mKT_TYPEField;
        }
        set {
            this.mKT_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MKT_TYPESpecified {
        get {
            return this.mKT_TYPEFieldSpecified;
        }
        set {
            this.mKT_TYPEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<OASISMarketType> EXECUTION_TYPE {
        get {
            return this.eXECUTION_TYPEField;
        }
        set {
            this.eXECUTION_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EXECUTION_TYPESpecified {
        get {
            return this.eXECUTION_TYPEFieldSpecified;
        }
        set {
            this.eXECUTION_TYPEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_MKT_NAME {
        get {
            return this.cRR_MKT_NAMEField;
        }
        set {
            this.cRR_MKT_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<UOMType> UOM {
        get {
            return this.uOMField;
        }
        set {
            this.uOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UOMSpecified {
        get {
            return this.uOMFieldSpecified;
        }
        set {
            this.uOMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public OASISIntervalType INTERVAL {
        get {
            return this.iNTERVALField;
        }
        set {
            this.iNTERVALField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INTERVALSpecified {
        get {
            return this.iNTERVALFieldSpecified;
        }
        set {
            this.iNTERVALFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SEC_PER_INTERVAL {
        get {
            return this.sEC_PER_INTERVALField;
        }
        set {
            this.sEC_PER_INTERVALField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum SystemType {
    
    /// <remarks/>
    OASIS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum TimeZoneType {
    
    /// <remarks/>
    GMT,
    
    /// <remarks/>
    PPT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum OASISReportType {
    
    /// <remarks/>
    AS_RESULTS,
    
    /// <remarks/>
    AS_OP_RSRV,
    
    /// <remarks/>
    AS_REQ,
    
    /// <remarks/>
    BIDS_PUBLIC,
    
    /// <remarks/>
    CMMT_RA_MLC,
    
    /// <remarks/>
    CMMT_RMR,
    
    /// <remarks/>
    CRR_CLEARING,
    
    /// <remarks/>
    CRR_INVENTORY,
    
    /// <remarks/>
    ENE_EA,
    
    /// <remarks/>
    ENE_SLRS,
    
    /// <remarks/>
    ENE_HASP,
    
    /// <remarks/>
    ENE_IFM,
    
    /// <remarks/>
    ENE_MPM,
    
    /// <remarks/>
    ATL_PEAK_ON_OFF,
    
    /// <remarks/>
    ENE_RTM,
    
    /// <remarks/>
    ENE_RUC,
    
    /// <remarks/>
    ENE_LOSS,
    
    /// <remarks/>
    ENE_DISP,
    
    /// <remarks/>
    PRC_INTVL_AS,
    
    /// <remarks/>
    PRC_FUEL,
    
    /// <remarks/>
    PRC_LMP,
    
    /// <remarks/>
    PRC_HASP_LMP,
    
    /// <remarks/>
    PRC_AS,
    
    /// <remarks/>
    PRC_CNSTR,
    
    /// <remarks/>
    PRC_NOMOGRAM,
    
    /// <remarks/>
    PRC_INTVL_LMP,
    
    /// <remarks/>
    PRC_HRLY_CNSTR,
    
    /// <remarks/>
    PRC_INTVL_CNSTR,
    
    /// <remarks/>
    PRC_CURR_LMP,
    
    /// <remarks/>
    PRC_CURR_HUB_LMP,
    
    /// <remarks/>
    PRC_ADV_LMP,
    
    /// <remarks/>
    PRC_RTM_FLOWGATE,
    
    /// <remarks/>
    PRC_RTM_NOMOGRAM,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("PRC_ADV_LMP")]
    PRC_ADV_LMP1,
    
    /// <remarks/>
    SLD_FCST,
    
    /// <remarks/>
    SLD_FCST_PEAK,
    
    /// <remarks/>
    SLD_MKTS,
    
    /// <remarks/>
    TRNS_ATC,
    
    /// <remarks/>
    TRNS_OUTAGE,
    
    /// <remarks/>
    TRNS_USAGE,
    
    /// <remarks/>
    TRNS_CURR_USAGE,
    
    /// <remarks/>
    PRC_DS_REF,
    
    /// <remarks/>
    ENE_CB_AWARDS,
    
    /// <remarks/>
    ENE_CB_CLR_AWARDS,
    
    /// <remarks/>
    ENE_CB_MKT_SUM,
    
    /// <remarks/>
    PRC_REF_PRICES,
    
    /// <remarks/>
    CB_NODAL_GRP_CNSTR_PRC,
    
    /// <remarks/>
    CB_NODAL_LIMITS,
    
    /// <remarks/>
    PRC_FLEX_RAMP,
    
    /// <remarks/>
    PRC_CD_INTVL_LMP,
    
    /// <remarks/>
    PRC_CD_RTM_FLOWGATE,
    
    /// <remarks/>
    PRC_CD_RTM_NOMOGRAM,
    
    /// <remarks/>
    ENE_CD_SLRS,
    
    /// <remarks/>
    PRC_MPM_CNSTR,
    
    /// <remarks/>
    PRC_MPM_CNSTR_CMP,
    
    /// <remarks/>
    PRC_MPM_NOMOGRAM,
    
    /// <remarks/>
    PRC_MPM_NOMOGRAM_CMP,
    
    /// <remarks/>
    PRC_MPM_RTM_FLOWGATE,
    
    /// <remarks/>
    PRC_MPM_RTM_FLOWGATE_CMP,
    
    /// <remarks/>
    PRC_MPM_LMP,
    
    /// <remarks/>
    PRC_MPM_RTM_LMP,
    
    /// <remarks/>
    PRC_MPM_RTM_NOMOGRAM,
    
    /// <remarks/>
    PRC_MPM_RTM_NOMOGRAM_CMP,
    
    /// <remarks/>
    PRC_MPM_RTM_REF_BUS,
    
    /// <remarks/>
    PRC_MPM_REF_BUS,
    
    /// <remarks/>
    PUB_CRR_BID,
    
    /// <remarks/>
    SLD_REN_FCST,
    
    /// <remarks/>
    AGGR_OUTAGE_SCH,
    
    /// <remarks/>
    PRC_GHG_ALLOWANCE,
    
    /// <remarks/>
    AS_MILEAGE_CALC,
    
    /// <remarks/>
    PRC_RTPD_LMP,
    
    /// <remarks/>
    PRC_EIM_GHG,
    
    /// <remarks/>
    ENE_EIM_TRANSFER_LIMITS,
    
    /// <remarks/>
    ENE_EIM_TRANSFER,
    
    /// <remarks/>
    ENE_EIM_DYN_NSI,
    
    /// <remarks/>
    ENE_BASE_NSI,
    
    /// <remarks/>
    PRC_SPTIE_LMP,
    
    /// <remarks/>
    PRC_CD_SPTIE_LMP,
    
    /// <remarks/>
    PRC_RTM_SCH_CNSTR,
    
    /// <remarks/>
    SLD_ADV_FCST,
    
    /// <remarks/>
    ENE_HRLY_BASE_NSI,
    
    /// <remarks/>
    ENE_HRLY_BASE_LOSS,
    
    /// <remarks/>
    ENE_UNCERTAINTY_MV,
    
    /// <remarks/>
    ENE_FLEX_RAMP_REQT,
    
    /// <remarks/>
    ENE_AGGR_FLEX_RAMP,
    
    /// <remarks/>
    ENE_FLEX_RAMP_DC,
    
    /// <remarks/>
    ENE_EIM_TRANSFER_TIE,
    
    /// <remarks/>
    SLD_SF_EVAL_DMD_FCST,
    
    /// <remarks/>
    ENE_WIND_SOLAR_SUMMARY,
    
    /// <remarks/>
    ENE_EIM_TRANSFER_LIMITS_TIE,
    
    /// <remarks/>
    PRC_MPM_DEFAULT_CMP,
    
    /// <remarks/>
    ENE_EIM_FLEX_RAMP_INPUT,
    
    /// <remarks/>
    PRC_RTM_LAP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum OASISMarketType {
    
    /// <remarks/>
    RUC,
    
    /// <remarks/>
    ACTUAL,
    
    /// <remarks/>
    HASP,
    
    /// <remarks/>
    RTM,
    
    /// <remarks/>
    DAM,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2DA")]
    Item2DA,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("N/A")]
    NA,
    
    /// <remarks/>
    ALL,
    
    /// <remarks/>
    TOTAL,
    
    /// <remarks/>
    FCST,
    
    /// <remarks/>
    RTPD,
    
    /// <remarks/>
    RTD,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7DA")]
    Item7DA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum UOMType {
    
    /// <remarks/>
    MW,
    
    /// <remarks/>
    MWh,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("US$")]
    US,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("%")]
    Item,
    
    /// <remarks/>
    INTEGER,
    
    /// <remarks/>
    FLAG,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("$/mmBTU")]
    mmBTU,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("$/lb")]
    lb,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("US$/MW")]
    USMW,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("US$/MWh")]
    USMWh,
    
    /// <remarks/>
    FACTOR,
    
    /// <remarks/>
    NODE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum OASISIntervalType {
    
    /// <remarks/>
    BEGINNING,
    
    /// <remarks/>
    ENDING,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class REPORT_ITEM {
    
    private REPORT_HEADEROASIS rEPORT_HEADERField;
    
    private REPORT_DATAOASIS[] rEPORT_DATAField;
    
    /// <remarks/>
    public REPORT_HEADEROASIS REPORT_HEADER {
        get {
            return this.rEPORT_HEADERField;
        }
        set {
            this.rEPORT_HEADERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("REPORT_DATA")]
    public REPORT_DATAOASIS[] REPORT_DATA {
        get {
            return this.rEPORT_DATAField;
        }
        set {
            this.rEPORT_DATAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class RTO {
    
    private name nameField;
    
    private REPORT_ITEM[] rEPORT_ITEMField;
    
    private DISCLAIMER_ITEMRq dISCLAIMER_ITEMField;
    
    private ERROR[] eRRORField;
    
    /// <remarks/>
    public name name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("REPORT_ITEM")]
    public REPORT_ITEM[] REPORT_ITEM {
        get {
            return this.rEPORT_ITEMField;
        }
        set {
            this.rEPORT_ITEMField = value;
        }
    }
    
    /// <remarks/>
    public DISCLAIMER_ITEMRq DISCLAIMER_ITEM {
        get {
            return this.dISCLAIMER_ITEMField;
        }
        set {
            this.dISCLAIMER_ITEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ERROR")]
    public ERROR[] ERROR {
        get {
            return this.eRRORField;
        }
        set {
            this.eRRORField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public enum name {
    
    /// <remarks/>
    CAISO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISReport_v1.xsd")]
public partial class MessagePayload {
    
    private RTO rTOField;
    
    /// <remarks/>
    public RTO RTO {
        get {
            return this.rTOField;
        }
        set {
            this.rTOField = value;
        }
    }
}
