/********************************************************* NOTE *********************************************************/
/*
 * I used the v4 version and renamed "v4" to "v1" in this file to get it to work because the XML has "v1" as the namespace in the header
 * Ex: <?xml version="1.0" encoding="UTF-8"?><OASISMaster xmlns="http://www.caiso.com/soa/OASISMaster_v1.xsd">
 */
/************************************************************************************************************************/

namespace Prices.Core.Application.XsdClasses.Master.V1;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd", IsNullable=false)]
public partial class OASISMaster {
    
    private MessageHeader messageHeaderField;
    
    private MessagePayload messagePayloadField;
    
    /// <remarks/>
    public MessageHeader MessageHeader {
        get {
            return this.messageHeaderField;
        }
        set {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    public MessagePayload MessagePayload {
        get {
            return this.messagePayloadField;
        }
        set {
            this.messagePayloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class MessageHeader {
    
    private string timeDateField;
    
    private string sourceField;
    
    private string versionField;
    
    public MessageHeader() {
        this.versionField = "v10150501";
    }
    
    /// <remarks/>
    public string TimeDate {
        get {
            return this.timeDateField;
        }
        set {
            this.timeDateField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class ERROR {
    
    private System.Nullable<OASISErrCode> eRR_CODEField;
    
    private bool eRR_CODEFieldSpecified;
    
    private System.Nullable<OASISErrDescription> eRR_DESCField;
    
    private bool eRR_DESCFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<OASISErrCode> ERR_CODE {
        get {
            return this.eRR_CODEField;
        }
        set {
            this.eRR_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ERR_CODESpecified {
        get {
            return this.eRR_CODEFieldSpecified;
        }
        set {
            this.eRR_CODEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<OASISErrDescription> ERR_DESC {
        get {
            return this.eRR_DESCField;
        }
        set {
            this.eRR_DESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ERR_DESCSpecified {
        get {
            return this.eRR_DESCFieldSpecified;
        }
        set {
            this.eRR_DESCFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public enum OASISErrCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1000")]
    Item1000,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1001")]
    Item1001,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1002")]
    Item1002,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1003")]
    Item1003,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1004")]
    Item1004,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1005")]
    Item1005,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1006")]
    Item1006,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1007")]
    Item1007,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1008")]
    Item1008,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1009")]
    Item1009,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1010")]
    Item1010,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1011")]
    Item1011,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1012")]
    Item1012,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1013")]
    Item1013,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1014")]
    Item1014,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1015")]
    Item1015,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1016")]
    Item1016,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1017")]
    Item1017,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1018")]
    Item1018,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1019")]
    Item1019,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1020")]
    Item1020,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public enum OASISErrDescription {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("No data returned for the specified selection")]
    Nodatareturnedforthespecifiedselection,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid Parameters of the given report name")]
    InvalidParametersofthegivenreportname,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid datetime format, please use valid datetime format")]
    Invaliddatetimeformatpleaseusevaliddatetimeformat,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Timed out waiting for query response")]
    Timedoutwaitingforqueryresponse,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Data can be requested for period of 31 days only")]
    Datacanberequestedforperiodof31daysonly,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Report name does not exist, please use valid report name")]
    Reportnamedoesnotexistpleaseusevalidreportname,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Validation exception during transformation of XML")]
    ValidationexceptionduringtransformationofXML,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Required file does not exist")]
    Requiredfiledoesnotexist,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Out of memory exception")]
    Outofmemoryexception,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Exceptions in reading and writing of XML files")]
    ExceptionsinreadingandwritingofXMLfiles,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System Error")]
    SystemError,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Empty Query,Please Enter ReportName,Startdate,EndDate and Other Parameters")]
    EmptyQueryPleaseEnterReportNameStartdateEndDateandOtherParameters,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Connection refused")]
    Connectionrefused,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Required Resources(xslt or xml or dir)Unavailable")]
    RequiredResourcesxsltorxmlordirUnavailable,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Start Date is beyond the limit, Please Use valid Start Date that falls within the" +
        " prescribed limit")]
    StartDateisbeyondthelimitPleaseUsevalidStartDatethatfallswithintheprescribedlimit,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GroupZip DownLoad is in Processing, Please Submit request after Sometime")]
    GroupZipDownLoadisinProcessingPleaseSubmitrequestafterSometime,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GROUPID Does Not Exist, Please Use Valid GROUPID Name")]
    GROUPIDDoesNotExistPleaseUseValidGROUPIDName,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Please select a maximum of 10 nodes or use the ALL option")]
    Pleaseselectamaximumof10nodesorusetheALLoption,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid Selection, cannot select multiple hours for this query")]
    InvalidSelectioncannotselectmultiplehoursforthisquery,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("market_term=ALL not supported for this query")]
    market_termALLnotsupportedforthisquery,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Version parameter is missing or is invalid")]
    Versionparameterismissingorisinvalid,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class DISCLAIMER_ITEMRq {
    
    private string dISCLAIMERField;
    
    /// <remarks/>
    public string DISCLAIMER {
        get {
            return this.dISCLAIMERField;
        }
        set {
            this.dISCLAIMERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class ATLS_DATA {
    
    private string? pUBLICATION_DATEField;
    
    private bool pUBLICATION_DATEFieldSpecified;
    
    private string? pUBLICATION_DATE_GMTField;
    
    private bool pUBLICATION_DATE_GMTFieldSpecified;
    
    private string rESOURCE_NAMEField;
    
    private string rESOURCE_AGG_TYPEField;
    
    private string rESOURCE_TYPEField;
    
    private string rUC_ZONE_NAMEField;
    
    private string tAC_AREA_NAMEField;
    
    private string aS_REGION_NAMEField;
    
    private string aPNODE_NAMEField;
    
    private string aPNODE_TYPEField;
    
    private System.Nullable<double> aPNODE_LDFField;
    
    private bool aPNODE_LDFFieldSpecified;
    
    private string pNODE_NAMEField;
    
    private string pNODE_TYPEField;
    
    private string tI_NAMEField;
    
    private string tI_DIRECTIONField;
    
    private string tI_TYPEField;
    
    private string tI_WECCField;
    
    private string tIEPOINT_NAMEField;
    
    private string tIEPOINT_TYPEField;
    
    private string tSIN_NAMEField;
    
    private string cRR_SOURCE_SINKField;
    
    private System.Nullable<double> dIST_FACTORField;
    
    private bool dIST_FACTORFieldSpecified;
    
    private string tIME_OF_USEField;
    
    private string? sTART_DATEField;
    
    private bool sTART_DATEFieldSpecified;
    
    private string? eND_DATEField;
    
    private bool eND_DATEFieldSpecified;
    
    private string nODE_NAMEField;
    
    private string tIE_NAMEField;
    
    private string? sTART_DATE_GMTField;
    
    private bool sTART_DATE_GMTFieldSpecified;
    
    private string? eND_DATE_GMTField;
    
    private bool eND_DATE_GMTFieldSpecified;
    
    private string? oPR_DATEField;
    
    private bool oPR_DATEFieldSpecified;
    
    private string oPR_HRField;
    
    private string oPR_INTERVALField;
    
    private string? iNTERVAL_START_GMTField;
    
    private bool iNTERVAL_START_GMTFieldSpecified;
    
    private string? iNTERVAL_END_GMTField;
    
    private bool iNTERVAL_END_GMTFieldSpecified;
    
    private string oASIS_SECTIONField;
    
    private string oASIS_REPORTField;
    
    private string oASIS_REPORT_DESCField;
    
    private string oASIS_MARKET_RUN_IDField;
    
    private string pUBLICATION_TYPEField;
    
    private string pUBLICATION_INTERVALField;
    
    private string oASIS_PUB_DATETIMEField;
    
    private string sTATUSField;
    
    private string vERSIONField;
    
    private string gRP_NAMEField;
    
    private string dESCRIPTIONField;
    
    private string cOMMENTSField;
    
    private string cRR_FLAGField;
    
    private string cRR_SEASONField;
    
    private string cRR_TOUField;
    
    private System.Nullable<double> rESOURCE_AGG_LDFField;
    
    private bool rESOURCE_AGG_LDFFieldSpecified;
    
    private string? mSG_TIMEField;
    
    private bool mSG_TIMEFieldSpecified;
    
    private string? mSG_TIME_GMTField;
    
    private bool mSG_TIME_GMTFieldSpecified;
    
    private string mSG_SEVField;
    
    private string mSG_TEXTField;
    
    private string? pUBLISH_TIMEField;
    
    private bool pUBLISH_TIMEFieldSpecified;
    
    private string? pUBLISH_TIME_GMTField;
    
    private bool pUBLISH_TIME_GMTFieldSpecified;
    
    private string cB_NODE_FLAGField;
    
    private string mAX_CB_MWField;
    
    private string? mAX_CB_MW_EFF_START_DTField;
    
    private bool mAX_CB_MW_EFF_START_DTFieldSpecified;
    
    private string? mAX_CB_MW_EFF_END_DTField;
    
    private bool mAX_CB_MW_EFF_END_DTFieldSpecified;
    
    private string? mAX_CB_MW_EFF_START_DT_GMTField;
    
    private bool mAX_CB_MW_EFF_START_DT_GMTFieldSpecified;
    
    private string? mAX_CB_MW_EFF_END_DT_GMTField;
    
    private bool mAX_CB_MW_EFF_END_DT_GMTFieldSpecified;
    
    private string bAA_IDField;
    
    private string sCHEDULING_POINTField;
    
    private string aLLOW_BIDField;
    
    private string fROM_BAAField;
    
    private string tO_BAAField;
    
    private string eIM_TRANSFER_FLAGField;
    
    private string iTIE_SCHEDULING_LIMITField;
    
    private string rESOURCE_IDField;
    
    private string gEN_UNIT_NAMEField;
    
    private string pARENT_RESOURCE_IDField;
    
    private string cLASSIFICATIONField;
    
    private string qfField;
    
    private System.Nullable<double> nET_DEPENDABLE_CAPACITYField;
    
    private bool nET_DEPENDABLE_CAPACITYFieldSpecified;
    
    private string pTO_AREAField;
    
    private string oWNER_OR_QFField;
    
    private string uNIT_TYPEField;
    
    private string eNERGY_SOURCEField;
    
    private string zONEField;
    
    private string uDCField;
    
    private string? cODField;
    
    private bool cODFieldSpecified;
    
    private string rIVER_SYSTEMField;
    
    private string nAMEPLATE_CAPACITYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? PUBLICATION_DATE {
        get {
            return this.pUBLICATION_DATEField;
        }
        set {
            this.pUBLICATION_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PUBLICATION_DATESpecified {
        get {
            return this.pUBLICATION_DATEFieldSpecified;
        }
        set {
            this.pUBLICATION_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? PUBLICATION_DATE_GMT {
        get {
            return this.pUBLICATION_DATE_GMTField;
        }
        set {
            this.pUBLICATION_DATE_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PUBLICATION_DATE_GMTSpecified {
        get {
            return this.pUBLICATION_DATE_GMTFieldSpecified;
        }
        set {
            this.pUBLICATION_DATE_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RESOURCE_NAME {
        get {
            return this.rESOURCE_NAMEField;
        }
        set {
            this.rESOURCE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RESOURCE_AGG_TYPE {
        get {
            return this.rESOURCE_AGG_TYPEField;
        }
        set {
            this.rESOURCE_AGG_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RESOURCE_TYPE {
        get {
            return this.rESOURCE_TYPEField;
        }
        set {
            this.rESOURCE_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RUC_ZONE_NAME {
        get {
            return this.rUC_ZONE_NAMEField;
        }
        set {
            this.rUC_ZONE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TAC_AREA_NAME {
        get {
            return this.tAC_AREA_NAMEField;
        }
        set {
            this.tAC_AREA_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AS_REGION_NAME {
        get {
            return this.aS_REGION_NAMEField;
        }
        set {
            this.aS_REGION_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string APNODE_NAME {
        get {
            return this.aPNODE_NAMEField;
        }
        set {
            this.aPNODE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string APNODE_TYPE {
        get {
            return this.aPNODE_TYPEField;
        }
        set {
            this.aPNODE_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> APNODE_LDF {
        get {
            return this.aPNODE_LDFField;
        }
        set {
            this.aPNODE_LDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool APNODE_LDFSpecified {
        get {
            return this.aPNODE_LDFFieldSpecified;
        }
        set {
            this.aPNODE_LDFFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PNODE_NAME {
        get {
            return this.pNODE_NAMEField;
        }
        set {
            this.pNODE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PNODE_TYPE {
        get {
            return this.pNODE_TYPEField;
        }
        set {
            this.pNODE_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TI_NAME {
        get {
            return this.tI_NAMEField;
        }
        set {
            this.tI_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TI_DIRECTION {
        get {
            return this.tI_DIRECTIONField;
        }
        set {
            this.tI_DIRECTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TI_TYPE {
        get {
            return this.tI_TYPEField;
        }
        set {
            this.tI_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TI_WECC {
        get {
            return this.tI_WECCField;
        }
        set {
            this.tI_WECCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TIEPOINT_NAME {
        get {
            return this.tIEPOINT_NAMEField;
        }
        set {
            this.tIEPOINT_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TIEPOINT_TYPE {
        get {
            return this.tIEPOINT_TYPEField;
        }
        set {
            this.tIEPOINT_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TSIN_NAME {
        get {
            return this.tSIN_NAMEField;
        }
        set {
            this.tSIN_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_SOURCE_SINK {
        get {
            return this.cRR_SOURCE_SINKField;
        }
        set {
            this.cRR_SOURCE_SINKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> DIST_FACTOR {
        get {
            return this.dIST_FACTORField;
        }
        set {
            this.dIST_FACTORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DIST_FACTORSpecified {
        get {
            return this.dIST_FACTORFieldSpecified;
        }
        set {
            this.dIST_FACTORFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TIME_OF_USE {
        get {
            return this.tIME_OF_USEField;
        }
        set {
            this.tIME_OF_USEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? START_DATE {
        get {
            return this.sTART_DATEField;
        }
        set {
            this.sTART_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool START_DATESpecified {
        get {
            return this.sTART_DATEFieldSpecified;
        }
        set {
            this.sTART_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? END_DATE {
        get {
            return this.eND_DATEField;
        }
        set {
            this.eND_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool END_DATESpecified {
        get {
            return this.eND_DATEFieldSpecified;
        }
        set {
            this.eND_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string NODE_NAME {
        get {
            return this.nODE_NAMEField;
        }
        set {
            this.nODE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TIE_NAME {
        get {
            return this.tIE_NAMEField;
        }
        set {
            this.tIE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? START_DATE_GMT {
        get {
            return this.sTART_DATE_GMTField;
        }
        set {
            this.sTART_DATE_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool START_DATE_GMTSpecified {
        get {
            return this.sTART_DATE_GMTFieldSpecified;
        }
        set {
            this.sTART_DATE_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? END_DATE_GMT {
        get {
            return this.eND_DATE_GMTField;
        }
        set {
            this.eND_DATE_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool END_DATE_GMTSpecified {
        get {
            return this.eND_DATE_GMTFieldSpecified;
        }
        set {
            this.eND_DATE_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? OPR_DATE {
        get {
            return this.oPR_DATEField;
        }
        set {
            this.oPR_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OPR_DATESpecified {
        get {
            return this.oPR_DATEFieldSpecified;
        }
        set {
            this.oPR_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string OPR_HR {
        get {
            return this.oPR_HRField;
        }
        set {
            this.oPR_HRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string OPR_INTERVAL {
        get {
            return this.oPR_INTERVALField;
        }
        set {
            this.oPR_INTERVALField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INTERVAL_START_GMT {
        get {
            return this.iNTERVAL_START_GMTField;
        }
        set {
            this.iNTERVAL_START_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INTERVAL_START_GMTSpecified {
        get {
            return this.iNTERVAL_START_GMTFieldSpecified;
        }
        set {
            this.iNTERVAL_START_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? INTERVAL_END_GMT {
        get {
            return this.iNTERVAL_END_GMTField;
        }
        set {
            this.iNTERVAL_END_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INTERVAL_END_GMTSpecified {
        get {
            return this.iNTERVAL_END_GMTFieldSpecified;
        }
        set {
            this.iNTERVAL_END_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OASIS_SECTION {
        get {
            return this.oASIS_SECTIONField;
        }
        set {
            this.oASIS_SECTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OASIS_REPORT {
        get {
            return this.oASIS_REPORTField;
        }
        set {
            this.oASIS_REPORTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OASIS_REPORT_DESC {
        get {
            return this.oASIS_REPORT_DESCField;
        }
        set {
            this.oASIS_REPORT_DESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OASIS_MARKET_RUN_ID {
        get {
            return this.oASIS_MARKET_RUN_IDField;
        }
        set {
            this.oASIS_MARKET_RUN_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PUBLICATION_TYPE {
        get {
            return this.pUBLICATION_TYPEField;
        }
        set {
            this.pUBLICATION_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PUBLICATION_INTERVAL {
        get {
            return this.pUBLICATION_INTERVALField;
        }
        set {
            this.pUBLICATION_INTERVALField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OASIS_PUB_DATETIME {
        get {
            return this.oASIS_PUB_DATETIMEField;
        }
        set {
            this.oASIS_PUB_DATETIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string STATUS {
        get {
            return this.sTATUSField;
        }
        set {
            this.sTATUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string VERSION {
        get {
            return this.vERSIONField;
        }
        set {
            this.vERSIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GRP_NAME {
        get {
            return this.gRP_NAMEField;
        }
        set {
            this.gRP_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string COMMENTS {
        get {
            return this.cOMMENTSField;
        }
        set {
            this.cOMMENTSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_FLAG {
        get {
            return this.cRR_FLAGField;
        }
        set {
            this.cRR_FLAGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_SEASON {
        get {
            return this.cRR_SEASONField;
        }
        set {
            this.cRR_SEASONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CRR_TOU {
        get {
            return this.cRR_TOUField;
        }
        set {
            this.cRR_TOUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> RESOURCE_AGG_LDF {
        get {
            return this.rESOURCE_AGG_LDFField;
        }
        set {
            this.rESOURCE_AGG_LDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RESOURCE_AGG_LDFSpecified {
        get {
            return this.rESOURCE_AGG_LDFFieldSpecified;
        }
        set {
            this.rESOURCE_AGG_LDFFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MSG_TIME {
        get {
            return this.mSG_TIMEField;
        }
        set {
            this.mSG_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MSG_TIMESpecified {
        get {
            return this.mSG_TIMEFieldSpecified;
        }
        set {
            this.mSG_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MSG_TIME_GMT {
        get {
            return this.mSG_TIME_GMTField;
        }
        set {
            this.mSG_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MSG_TIME_GMTSpecified {
        get {
            return this.mSG_TIME_GMTFieldSpecified;
        }
        set {
            this.mSG_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MSG_SEV {
        get {
            return this.mSG_SEVField;
        }
        set {
            this.mSG_SEVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MSG_TEXT {
        get {
            return this.mSG_TEXTField;
        }
        set {
            this.mSG_TEXTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? PUBLISH_TIME {
        get {
            return this.pUBLISH_TIMEField;
        }
        set {
            this.pUBLISH_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PUBLISH_TIMESpecified {
        get {
            return this.pUBLISH_TIMEFieldSpecified;
        }
        set {
            this.pUBLISH_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? PUBLISH_TIME_GMT {
        get {
            return this.pUBLISH_TIME_GMTField;
        }
        set {
            this.pUBLISH_TIME_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PUBLISH_TIME_GMTSpecified {
        get {
            return this.pUBLISH_TIME_GMTFieldSpecified;
        }
        set {
            this.pUBLISH_TIME_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CB_NODE_FLAG {
        get {
            return this.cB_NODE_FLAGField;
        }
        set {
            this.cB_NODE_FLAGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MAX_CB_MW {
        get {
            return this.mAX_CB_MWField;
        }
        set {
            this.mAX_CB_MWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MAX_CB_MW_EFF_START_DT {
        get {
            return this.mAX_CB_MW_EFF_START_DTField;
        }
        set {
            this.mAX_CB_MW_EFF_START_DTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MAX_CB_MW_EFF_START_DTSpecified {
        get {
            return this.mAX_CB_MW_EFF_START_DTFieldSpecified;
        }
        set {
            this.mAX_CB_MW_EFF_START_DTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MAX_CB_MW_EFF_END_DT {
        get {
            return this.mAX_CB_MW_EFF_END_DTField;
        }
        set {
            this.mAX_CB_MW_EFF_END_DTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MAX_CB_MW_EFF_END_DTSpecified {
        get {
            return this.mAX_CB_MW_EFF_END_DTFieldSpecified;
        }
        set {
            this.mAX_CB_MW_EFF_END_DTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MAX_CB_MW_EFF_START_DT_GMT {
        get {
            return this.mAX_CB_MW_EFF_START_DT_GMTField;
        }
        set {
            this.mAX_CB_MW_EFF_START_DT_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MAX_CB_MW_EFF_START_DT_GMTSpecified {
        get {
            return this.mAX_CB_MW_EFF_START_DT_GMTFieldSpecified;
        }
        set {
            this.mAX_CB_MW_EFF_START_DT_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? MAX_CB_MW_EFF_END_DT_GMT {
        get {
            return this.mAX_CB_MW_EFF_END_DT_GMTField;
        }
        set {
            this.mAX_CB_MW_EFF_END_DT_GMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MAX_CB_MW_EFF_END_DT_GMTSpecified {
        get {
            return this.mAX_CB_MW_EFF_END_DT_GMTFieldSpecified;
        }
        set {
            this.mAX_CB_MW_EFF_END_DT_GMTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BAA_ID {
        get {
            return this.bAA_IDField;
        }
        set {
            this.bAA_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SCHEDULING_POINT {
        get {
            return this.sCHEDULING_POINTField;
        }
        set {
            this.sCHEDULING_POINTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ALLOW_BID {
        get {
            return this.aLLOW_BIDField;
        }
        set {
            this.aLLOW_BIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FROM_BAA {
        get {
            return this.fROM_BAAField;
        }
        set {
            this.fROM_BAAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TO_BAA {
        get {
            return this.tO_BAAField;
        }
        set {
            this.tO_BAAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EIM_TRANSFER_FLAG {
        get {
            return this.eIM_TRANSFER_FLAGField;
        }
        set {
            this.eIM_TRANSFER_FLAGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ITIE_SCHEDULING_LIMIT {
        get {
            return this.iTIE_SCHEDULING_LIMITField;
        }
        set {
            this.iTIE_SCHEDULING_LIMITField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RESOURCE_ID {
        get {
            return this.rESOURCE_IDField;
        }
        set {
            this.rESOURCE_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GEN_UNIT_NAME {
        get {
            return this.gEN_UNIT_NAMEField;
        }
        set {
            this.gEN_UNIT_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PARENT_RESOURCE_ID {
        get {
            return this.pARENT_RESOURCE_IDField;
        }
        set {
            this.pARENT_RESOURCE_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CLASSIFICATION {
        get {
            return this.cLASSIFICATIONField;
        }
        set {
            this.cLASSIFICATIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string QF {
        get {
            return this.qfField;
        }
        set {
            this.qfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<double> NET_DEPENDABLE_CAPACITY {
        get {
            return this.nET_DEPENDABLE_CAPACITYField;
        }
        set {
            this.nET_DEPENDABLE_CAPACITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NET_DEPENDABLE_CAPACITYSpecified {
        get {
            return this.nET_DEPENDABLE_CAPACITYFieldSpecified;
        }
        set {
            this.nET_DEPENDABLE_CAPACITYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PTO_AREA {
        get {
            return this.pTO_AREAField;
        }
        set {
            this.pTO_AREAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OWNER_OR_QF {
        get {
            return this.oWNER_OR_QFField;
        }
        set {
            this.oWNER_OR_QFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string UNIT_TYPE {
        get {
            return this.uNIT_TYPEField;
        }
        set {
            this.uNIT_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ENERGY_SOURCE {
        get {
            return this.eNERGY_SOURCEField;
        }
        set {
            this.eNERGY_SOURCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ZONE {
        get {
            return this.zONEField;
        }
        set {
            this.zONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string UDC {
        get {
            return this.uDCField;
        }
        set {
            this.uDCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string? COD {
        get {
            return this.cODField;
        }
        set {
            this.cODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CODSpecified {
        get {
            return this.cODFieldSpecified;
        }
        set {
            this.cODFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RIVER_SYSTEM {
        get {
            return this.rIVER_SYSTEMField;
        }
        set {
            this.rIVER_SYSTEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string NAMEPLATE_CAPACITY {
        get {
            return this.nAMEPLATE_CAPACITYField;
        }
        set {
            this.nAMEPLATE_CAPACITYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class ATLS_HEADEROASIS {
    
    private SystemType sYSTEMField;
    
    private TimeZoneType tzField;
    
    private OASISMasterType rEPORTField;
    
    /// <remarks/>
    public SystemType SYSTEM {
        get {
            return this.sYSTEMField;
        }
        set {
            this.sYSTEMField = value;
        }
    }
    
    /// <remarks/>
    public TimeZoneType TZ {
        get {
            return this.tzField;
        }
        set {
            this.tzField = value;
        }
    }
    
    /// <remarks/>
    public OASISMasterType REPORT {
        get {
            return this.rEPORTField;
        }
        set {
            this.rEPORTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public enum SystemType {
    
    /// <remarks/>
    OASIS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public enum TimeZoneType {
    
    /// <remarks/>
    GMT,
    
    /// <remarks/>
    PPT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public enum OASISMasterType {
    
    /// <remarks/>
    ATL_AS_REGION_MAP,
    
    /// <remarks/>
    ATL_LAP,
    
    /// <remarks/>
    ATL_LDF,
    
    /// <remarks/>
    ATL_PNODE,
    
    /// <remarks/>
    ATL_APNODE,
    
    /// <remarks/>
    ATL_RUC_ZONE_MAP,
    
    /// <remarks/>
    ATL_TAC_AREA_MAP,
    
    /// <remarks/>
    ATL_PNODE_MAP,
    
    /// <remarks/>
    ATL_RESOURCE,
    
    /// <remarks/>
    ATL_HUB,
    
    /// <remarks/>
    ATL_TIEPOINT,
    
    /// <remarks/>
    ATL_TI,
    
    /// <remarks/>
    ATL_PUB,
    
    /// <remarks/>
    ATL_PUB_SCHED,
    
    /// <remarks/>
    ATL_STAT,
    
    /// <remarks/>
    ATL_XREF,
    
    /// <remarks/>
    ATL_OSM,
    
    /// <remarks/>
    ATL_CBNODE,
    
    /// <remarks/>
    ATL_PRC_CORR_MSG,
    
    /// <remarks/>
    ATL_SP,
    
    /// <remarks/>
    ATL_BAA_TIE,
    
    /// <remarks/>
    ATL_SP_TIE,
    
    /// <remarks/>
    ATL_ITC_SP,
    
    /// <remarks/>
    ATL_ISL_TIE,
    
    /// <remarks/>
    ATL_GEN_CAP_LST,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class ATLS_ITEM {
    
    private ATLS_HEADEROASIS aTLS_HEADERField;
    
    private ATLS_DATA[] aTLS_DATAField;
    
    /// <remarks/>
    public ATLS_HEADEROASIS ATLS_HEADER {
        get {
            return this.aTLS_HEADERField;
        }
        set {
            this.aTLS_HEADERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ATLS_DATA")]
    public ATLS_DATA[] ATLS_DATA {
        get {
            return this.aTLS_DATAField;
        }
        set {
            this.aTLS_DATAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class RTO {
    
    private name nameField;
    
    private ATLS_ITEM[] aTLS_ITEMField;
    
    private DISCLAIMER_ITEMRq dISCLAIMER_ITEMField;
    
    private ERROR[] eRRORField;
    
    /// <remarks/>
    public name name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ATLS_ITEM")]
    public ATLS_ITEM[] ATLS_ITEM {
        get {
            return this.aTLS_ITEMField;
        }
        set {
            this.aTLS_ITEMField = value;
        }
    }
    
    /// <remarks/>
    public DISCLAIMER_ITEMRq DISCLAIMER_ITEM {
        get {
            return this.dISCLAIMER_ITEMField;
        }
        set {
            this.dISCLAIMER_ITEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ERROR")]
    public ERROR[] ERROR {
        get {
            return this.eRRORField;
        }
        set {
            this.eRRORField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public enum name {
    
    /// <remarks/>
    CAISO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caiso.com/soa/OASISMaster_v1.xsd")]
public partial class MessagePayload {
    
    private RTO rTOField;
    
    /// <remarks/>
    public RTO RTO {
        get {
            return this.rTOField;
        }
        set {
            this.rTOField = value;
        }
    }
}
